# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0df6adff915fc2e4722ac3606b5eb031eac3a49f4a7995ebb117cd5e51ab8ee51dd386ed49dc174ec4faa3cced11698be9760bfdcbdfaac2422fec683fae4cf5

test:
  secret_key_base: 959b06d7d7338a40045d485d0b46e9b7fa0082bcaac2333e7f3df52348d328eb4db9f4f5eeef0b0edda09e65250ad3f28f303a2e432c0410ae304002a64fc4d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
